spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${BOOKING_DB:bookingdb}
    username: ${DB_USER:booking}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
  producer:
    retries: 3

booking:
  pnr-prefix: SKY
  hold-time-seconds: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.skyking.booking: INFO
