spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${INVENTORY_DB:inventorydb}
    username: ${DB_USER:inventory}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 60000

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

inventory:
  seat-hold-ttl-seconds: 300 # 5 minutes

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.skyking.inventory: INFO
