spring:
  application:
    name: notification-service

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
  consumer:
    group-id: notification-group

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.skyking.notify: INFO
