spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${PAYMENT_DB:paymentdb}
    username: ${DB_USER:payment}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

payment:
  provider:
    name: mock
  idempotency:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.skyking.payment: INFO
