spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/skyking-airlines
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: myjwtsecrettemporaryaddingherewillchangelater          # replace with real secret later
  expiration-ms: 86400000

kafka:
  bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.skyking: INFO

